### ISSUE TITLE
Разумно ли при каждом вызове искать элемент?

### ISSUE THREAD

**Issue by coursar** [aygulmardanova/cashback#10]
https://github.com/aygulmardanova/cashback/blob/708dd9ad6a03a7ba64a48b394503fe267ee16d14/src/js/app.js#L22

**Comment by aygulmardanova** [comment]
а как можно вписать значение в этот output?

**Comment by coursar** [comment]
Вопрос снимается, это мы ещё не проходили )) выносить надо переменную наверх скрипта и там кэшировать. Замыкания позволяют вам получить доступ к внешним переменным.
